# Generated by Django 4.2.5 on 2023-09-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("h5_model", models.FileField(upload_to="./h5_folder")),
                ("face_labels", models.JSONField()),
                (
                    "headshot_directory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
